baseURL = 'https://example.org/'
languageCode = 'en-au'
title = 'Callums Travel & Dev Blog'
theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/stuartcallum"

[[params.socialIcons]]
name = "letterboxd"
url = "https://letterboxd.com/calstu"
